import 'dotenv/config';
import { connectToMongoDB, db, disconnectFromMongoDB } from './db.js';
import type { Product } from './types.js';

const products: Omit<Product, '_id'>[] = [
    // ── Laptops ────────────────────────────────────────────────────
    {
        name: 'MacBook Pro 16" M3 Max',
        slug: 'macbook-pro-16-m3-max',
        description: 'Apple MacBook Pro 16" with M3 Max chip, 36GB RAM, 1TB SSD. The most powerful MacBook ever made for professionals.',
        price: 3499,
        originalPrice: 3799,
        category: 'laptops',
        brand: 'Apple',
        image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80',
        rating: 4.9,
        reviewCount: 1284,
        stock: 15,
        tags: ['apple', 'macbook', 'laptop', 'pro', 'm3'],
        featured: true,
        deal: false,
        specs: { CPU: 'Apple M3 Max', RAM: '36GB', Storage: '1TB SSD', Display: '16.2" Liquid Retina XDR', Battery: '22 hours' },
        createdAt: new Date(),
    },
    {
        name: 'Dell XPS 15 OLED',
        slug: 'dell-xps-15-oled',
        description: 'Dell XPS 15 with Intel Core i9, 32GB RAM, 1TB SSD, and stunning 3.5K OLED display.',
        price: 2299,
        originalPrice: 2599,
        category: 'laptops',
        brand: 'Dell',
        image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80',
        rating: 4.7,
        reviewCount: 832,
        stock: 22,
        tags: ['dell', 'xps', 'laptop', 'oled', 'intel'],
        featured: true,
        deal: true,
        discountPercent: 12,
        specs: { CPU: 'Intel Core i9-13900H', RAM: '32GB DDR5', Storage: '1TB NVMe SSD', Display: '15.6" 3.5K OLED', GPU: 'RTX 4070' },
        createdAt: new Date(),
    },
    {
        name: 'ASUS ROG Zephyrus G14',
        slug: 'asus-rog-zephyrus-g14',
        description: 'Compact gaming powerhouse with AMD Ryzen 9, RTX 4090, and 165Hz QHD display.',
        price: 1999,
        originalPrice: 2299,
        category: 'laptops',
        brand: 'ASUS',
        image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&q=80',
        rating: 4.8,
        reviewCount: 567,
        stock: 18,
        tags: ['asus', 'rog', 'gaming', 'laptop', 'amd'],
        featured: false,
        deal: true,
        discountPercent: 13,
        specs: { CPU: 'AMD Ryzen 9 7940HS', RAM: '32GB DDR5', Storage: '1TB SSD', Display: '14" QHD 165Hz', GPU: 'RTX 4090 Laptop' },
        createdAt: new Date(),
    },

    // ── Phones ─────────────────────────────────────────────────────
    {
        name: 'iPhone 16 Pro Max',
        slug: 'iphone-16-pro-max',
        description: 'Apple iPhone 16 Pro Max with A18 Pro chip, 48MP camera system, and titanium design.',
        price: 1199,
        originalPrice: 1199,
        category: 'phones',
        brand: 'Apple',
        image: 'https://images.unsplash.com/photo-1696446702183-cbd01e4e38a1?w=600&q=80',
        rating: 4.9,
        reviewCount: 3421,
        stock: 45,
        tags: ['iphone', 'apple', 'smartphone', 'pro', '5g'],
        featured: true,
        deal: false,
        specs: { Chip: 'A18 Pro', Camera: '48MP Main + 12MP Ultra Wide', Display: '6.9" Super Retina XDR', Battery: '4685mAh', Storage: '256GB' },
        createdAt: new Date(),
    },
    {
        name: 'Samsung Galaxy S25 Ultra',
        slug: 'samsung-galaxy-s25-ultra',
        description: 'Samsung Galaxy S25 Ultra with Snapdragon 8 Elite, 200MP camera, built-in S Pen.',
        price: 1299,
        originalPrice: 1399,
        category: 'phones',
        brand: 'Samsung',
        image: 'https://images.unsplash.com/photo-1610945264803-c22b62d2a7b3?w=600&q=80',
        rating: 4.8,
        reviewCount: 2187,
        stock: 38,
        tags: ['samsung', 'galaxy', 's25', 'android', '5g', 's-pen'],
        featured: true,
        deal: true,
        discountPercent: 7,
        specs: { Chip: 'Snapdragon 8 Elite', Camera: '200MP + 50MP + 10MP', Display: '6.9" Dynamic AMOLED 2X 120Hz', Battery: '5000mAh', RAM: '12GB' },
        createdAt: new Date(),
    },
    {
        name: 'Google Pixel 9 Pro',
        slug: 'google-pixel-9-pro',
        description: 'Google Pixel 9 Pro with Tensor G4, advanced AI photography, and pure Android experience.',
        price: 999,
        originalPrice: 1099,
        category: 'phones',
        brand: 'Google',
        image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=80',
        rating: 4.7,
        reviewCount: 943,
        stock: 29,
        tags: ['google', 'pixel', 'android', 'ai', '5g'],
        featured: false,
        deal: true,
        discountPercent: 9,
        specs: { Chip: 'Google Tensor G4', Camera: '50MP Main + 48MP Ultra Wide', Display: '6.3" LTPO OLED', Battery: '4700mAh', RAM: '16GB' },
        createdAt: new Date(),
    },

    // ── Audio ──────────────────────────────────────────────────────
    {
        name: 'Sony WH-1000XM5',
        slug: 'sony-wh-1000xm5',
        description: 'Industry-leading noise cancellation headphones with 30-hour battery and Hi-Res Audio.',
        price: 349,
        originalPrice: 399,
        category: 'audio',
        brand: 'Sony',
        image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&q=80',
        rating: 4.9,
        reviewCount: 5832,
        stock: 67,
        tags: ['sony', 'headphones', 'noise-cancelling', 'wireless', 'bluetooth'],
        featured: true,
        deal: true,
        discountPercent: 13,
        specs: { Driver: '30mm', Battery: '30 hours', Connectivity: 'Bluetooth 5.2', Noise: 'Active Noise Cancellation', Weight: '250g' },
        createdAt: new Date(),
    },
    {
        name: 'AirPods Pro (3rd Gen)',
        slug: 'airpods-pro-3rd-gen',
        description: 'Apple AirPods Pro with H2 chip, adaptive audio, and transparency mode.',
        price: 249,
        originalPrice: 249,
        category: 'audio',
        brand: 'Apple',
        image: 'https://images.unsplash.com/photo-1603351154351-5e2d0600bb77?w=600&q=80',
        rating: 4.8,
        reviewCount: 7124,
        stock: 120,
        tags: ['apple', 'airpods', 'earbuds', 'wireless', 'noise-cancelling'],
        featured: true,
        deal: false,
        specs: { Chip: 'Apple H2', Battery: '6h (30h with case)', Connectivity: 'Bluetooth 5.3', Water: 'IPX4', ANC: 'Adaptive Transparency' },
        createdAt: new Date(),
    },

    // ── Gaming ─────────────────────────────────────────────────────
    {
        name: 'PlayStation 5 Pro',
        slug: 'playstation-5-pro',
        description: 'Sony PS5 Pro with enhanced GPU, 2TB SSD, and 8K gaming support.',
        price: 699,
        originalPrice: 699,
        category: 'gaming',
        brand: 'Sony',
        image: 'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=600&q=80',
        rating: 4.9,
        reviewCount: 2341,
        stock: 12,
        tags: ['playstation', 'sony', 'console', 'gaming', 'ps5'],
        featured: true,
        deal: false,
        specs: { CPU: 'AMD Zen 2 (3.5GHz)', GPU: 'Enhanced RDNA 2', Storage: '2TB SSD', Resolution: 'Up to 8K', RAM: '16GB GDDR6' },
        createdAt: new Date(),
    },
    {
        name: 'Xbox Series X',
        slug: 'xbox-series-x',
        description: 'Microsoft Xbox Series X — 12 teraflops of GPU power, 1TB SSD, and 4K at 120fps.',
        price: 499,
        originalPrice: 549,
        category: 'gaming',
        brand: 'Microsoft',
        image: 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=600&q=80',
        rating: 4.8,
        reviewCount: 1876,
        stock: 24,
        tags: ['xbox', 'microsoft', 'console', 'gaming', '4k'],
        featured: false,
        deal: true,
        discountPercent: 9,
        specs: { CPU: 'AMD Zen 2 (3.8GHz)', GPU: '12 TFLOPS RDNA 2', Storage: '1TB NVMe SSD', Resolution: '4K @ 120fps', RAM: '16GB GDDR6' },
        createdAt: new Date(),
    },

    // ── Monitors ───────────────────────────────────────────────────
    {
        name: 'LG UltraGear 27" 4K OLED',
        slug: 'lg-ultragear-27-4k-oled',
        description: 'LG UltraGear 27" 4K OLED gaming monitor with 240Hz refresh rate and 0.03ms response.',
        price: 899,
        originalPrice: 999,
        category: 'monitors',
        brand: 'LG',
        image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&q=80',
        rating: 4.8,
        reviewCount: 743,
        stock: 31,
        tags: ['lg', 'monitor', 'oled', '4k', 'gaming', '240hz'],
        featured: true,
        deal: true,
        discountPercent: 10,
        specs: { Panel: 'OLED', Resolution: '3840×2160 (4K)', Refresh: '240Hz', Response: '0.03ms', Ports: 'HDMI 2.1, DP 1.4, USB-C' },
        createdAt: new Date(),
    },

    // ── Accessories ────────────────────────────────────────────────
    {
        name: 'Logitech MX Master 3S',
        slug: 'logitech-mx-master-3s',
        description: 'Logitech MX Master 3S wireless mouse with MagSpeed scroll, ergonomic design for productivity.',
        price: 99,
        originalPrice: 109,
        category: 'accessories',
        brand: 'Logitech',
        image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80',
        rating: 4.8,
        reviewCount: 4312,
        stock: 95,
        tags: ['logitech', 'mouse', 'wireless', 'productivity', 'ergonomic'],
        featured: false,
        deal: true,
        discountPercent: 9,
        specs: { DPI: '200–8000', Battery: '70 days', Connectivity: 'Bluetooth, USB-C', Buttons: '7', Scroll: 'MagSpeed' },
        createdAt: new Date(),
    },
    {
        name: 'Keychron Q1 Pro Mechanical Keyboard',
        slug: 'keychron-q1-pro',
        description: 'Keychron Q1 Pro — wireless mechanical keyboard with gasket mount, per-key RGB, and hot-swap switches.',
        price: 199,
        originalPrice: 219,
        category: 'accessories',
        brand: 'Keychron',
        image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80',
        rating: 4.7,
        reviewCount: 1823,
        stock: 44,
        tags: ['keyboard', 'mechanical', 'wireless', 'rgb', 'keychron'],
        featured: false,
        deal: false,
        specs: { Layout: '75%', Switch: 'Gateron G Pro 3.0', Battery: '4000mAh', Connectivity: 'Bluetooth 5.1 / USB-C', Backlight: 'Per-key RGB' },
        createdAt: new Date(),
    },
];

async function seed() {
    await connectToMongoDB();
    const col = db().collection('products');

    // Clear existing
    await col.deleteMany({});
    console.log('🗑️  Cleared existing products');

    // Insert new
    const result = await col.insertMany(products as Product[]);
    console.log(`🌱 Seeded ${result.insertedCount} products`);

    // Create indexes
    await col.createIndex({ category: 1 });
    await col.createIndex({ featured: 1 });
    await col.createIndex({ deal: 1 });
    await col.createIndex({ name: 'text', brand: 'text', tags: 'text' });
    console.log('📇 Indexes created');

    await disconnectFromMongoDB();
}

seed().catch(console.error);
